version: "3.8"

services:
  database:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - database
    volumes:
      - .:/app
    env_file:
      - .env
    command:
      - bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"

  pgadmin:
    image: pgadmin
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - "8050:80"
