version: "3.3"

services:
  database:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - database
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"

  #pgadmin:
  #  image: dpage/pgadmin4
  #  depends_on:
  #    - database
  #  env_file:
  #    - .env
  #  ports:
  #    - "8050:80"
